---
- hosts: all
  gather_facts: yes
  become: yes

  vars:
    jenkins_version: 1.644

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes
      when: ansible_os_family == 'Debian'

  roles:
    - geerlingguy.jenkins

  tasks: []
